package main

import (
	_ "net/http"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	"github.com/swaggo/echo-swagger"

	_ "nomsu-api/docs" // docs is generated by Swag CLI, but you have to import it.

	"nomsu-api/handlers"
)

// @title Schrodinger's Cup API
// @version 1.0
// @description A game of Peter Suber's Nomic running on the Tezos network.
// @BasePath /
func main() {
	e := echo.New()

	// Middleware
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())

	// Routes
	e.GET("/", handlers.HelloWorld)
	e.GET("/ping", handlers.Ping)
	e.POST("/test", handlers.TestNomsu)
	e.POST("/vote", handlers.CastVote)
	e.POST("/settle", handlers.SettleGame)

	// swagger docs
	e.GET("/swagger/*", echoSwagger.WrapHandler)

	// Start server
	e.Logger.Fatal(e.Start(":1323"))
}
