basePath: /
definitions:
  handlers.AuthInput:
    properties:
      msg:
        type: string
      pubKey:
        type: string
      sig:
        type: string
    type: object
  handlers.AuthResult:
    properties:
      token:
        type: string
    type: object
  handlers.TestInput:
    properties:
      code:
        type: string
    type: object
  handlers.TestResult:
    properties:
      result:
        type: string
      resultHtml:
        type: string
    type: object
info:
  contact: {}
  description: A game of Peter Suber's Nomic running on the Tezos network.
  license: {}
  title: Schrodinger's Cup API
  version: "1.0"
paths:
  /auth:
    post:
      description: Authenticate a user with a signed tezos message
      parameters:
      - description: Signed message
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.AuthInput'
      produces:
      - application/json
      responses:
        "200":
          description: JWT token
          schema:
            $ref: '#/definitions/handlers.AuthResult'
  /game/settle:
    post:
      description: Settle game window
  /game/vote:
    post:
      description: Receive and tabulate votes, stage vote outcome to be processed when game window is settled
  /ping:
    get:
      description: Ping/Health Check
      produces:
      - text/plain
      responses:
        "200":
          description: pong
          schema:
            type: string
  /test:
    post:
      description: Run some arbitrary nomsu code
      parameters:
      - description: Nomsu code to run
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.TestInput'
      produces:
      - application/json
      responses:
        "200":
          description: Nomsu execution result
          schema:
            $ref: '#/definitions/handlers.TestResult'
swagger: "2.0"
