basePath: /
info:
  contact: {}
  description: A game of Peter Suber's Nomic running on the Tezos network.
  license: {}
  title: Schrodinger's Cup API
  version: "1.0"
paths:
  /ping:
    get:
      description: Ping/Health Check
      produces:
      - text/plain
      responses:
        "200":
          description: pong
          schema:
            type: string
  /settle:
    post:
      description: Settle game window
  /test:
    post:
      description: Run some arbitrary nomsu code
      parameters:
      - description: Nomsu code
        in: formData
        name: code
        required: true
        type: string
      responses:
        "200":
          description: nomsu execution result
          schema:
            type: string
  /vote:
    post:
      description: Receive and tabulate votes, stage vote outcome to be processed when game window is settled
swagger: "2.0"
