basePath: /
definitions:
  handlers.AuthInput:
    properties:
      address:
        type: string
      msg:
        type: string
      pubKey:
        type: string
      sig:
        type: string
    type: object
  handlers.AuthResult:
    properties:
      token:
        type: string
    type: object
  handlers.PlayerList:
    properties:
      currentTurn:
        type: string
      nextTurn:
        type: string
      nextTurnAt:
        type: string
      players:
        items:
          type: string
        type: array
    type: object
  handlers.TestInput:
    properties:
      code:
        type: string
    type: object
  handlers.TestResult:
    properties:
      result:
        type: string
      resultHtml:
        type: string
    type: object
info:
  contact: {}
  description: A game of Peter Suber's Nomic running on the Tezos network.
  license: {}
  title: Schrodinger's Cup API
  version: "1.0"
paths:
  /auth:
    post:
      description: Authenticate a user with a signed tezos message
      parameters:
      - description: Signed message
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.AuthInput'
      produces:
      - application/json
      responses:
        "200":
          description: JWT token
          schema:
            $ref: '#/definitions/handlers.AuthResult'
  /game/settle:
    post:
      description: Settle game window
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
  /game/vote:
    post:
      description: Receive and tabulate votes, stage vote outcome to be processed when game window is settled
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
  /ping:
    get:
      description: Ping/Health Check
      produces:
      - text/plain
      responses:
        "200":
          description: pong
          schema:
            type: string
  /players:
    get:
      description: Players
      produces:
      - application/json
      responses:
        "200":
          description: List of players in the current gameplay session
          schema:
            $ref: '#/definitions/handlers.PlayerList'
  /test:
    post:
      description: Run some arbitrary nomsu code
      parameters:
      - description: Nomsu code to run
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.TestInput'
      produces:
      - application/json
      responses:
        "200":
          description: Nomsu execution result
          schema:
            $ref: '#/definitions/handlers.TestResult'
swagger: "2.0"
