basePath: /
definitions:
  handlers.AuthInput:
    properties:
      address:
        type: string
      msg:
        type: string
      pubKey:
        type: string
      sig:
        type: string
    type: object
  handlers.AuthResult:
    properties:
      token:
        type: string
    type: object
  handlers.CurrentRound:
    properties:
      round:
        type: integer
    type: object
  handlers.PlayerList:
    properties:
      currentTurn:
        type: string
      nextTurn:
        type: string
      nextTurnAt:
        type: string
      players:
        items:
          type: string
        type: array
    type: object
  handlers.PointsItem:
    properties:
      player:
        type: string
      points:
        type: integer
    type: object
  handlers.PointsList:
    items:
      $ref: '#/definitions/handlers.PointsItem'
    type: array
  handlers.ProposalObject:
    properties:
      author:
        type: string
      code:
        type: string
      index:
        type: integer
      passed:
        type: boolean
      proposal:
        type: string
      round:
        type: integer
      timestamp:
        type: string
      type:
        type: string
    type: object
  handlers.ProposalResult:
    properties:
      message:
        description: '"OK!" or error message'
        type: string
      round:
        description: Updated round value
        type: integer
      success:
        type: boolean
    type: object
  handlers.RuleList:
    properties:
      immutable:
        items:
          $ref: '#/definitions/handlers.RuleObject'
        type: array
      mutable:
        items:
          $ref: '#/definitions/handlers.RuleObject'
        type: array
    type: object
  handlers.RuleObject:
    properties:
      code:
        type: string
      filename:
        type: string
      kind:
        type: string
    type: object
  handlers.RuleProposal:
    properties:
      code:
        description: Nomsu code
        type: string
      index:
        description: rule index of the existing rule
        type: integer
      kind:
        description: Mutable / Immutable
        type: string
      type:
        description: Update, Create, Delete, Transmute
        type: string
    type: object
  handlers.TestInput:
    properties:
      code:
        type: string
    type: object
  handlers.TestResult:
    properties:
      result:
        type: string
      resultHtml:
        type: string
    type: object
  handlers.VarsResult:
    properties:
      playerStartPts:
        type: integer
      pointsToWin:
        type: integer
      quorumRatio:
        type: number
      ruleFailedPenalty:
        type: integer
      rulePassPts:
        type: integer
      turnDuration:
        type: integer
      voteAgainstPts:
        type: integer
    type: object
  handlers.VoteObject:
    properties:
      player:
        type: string
      timestamp:
        type: integer
      vote:
        type: boolean
    type: object
  handlers.VotesList:
    properties:
      votes:
        items:
          $ref: '#/definitions/handlers.VoteObject'
        type: array
    type: object
info:
  contact: {}
  description: A game of Peter Suber's Nomic running on the Tezos network.
  license: {}
  title: Schrodinger's Cup API
  version: "1.0"
paths:
  /auth:
    post:
      description: Authenticate a user with a signed tezos message
      parameters:
      - description: Signed message
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.AuthInput'
      produces:
      - application/json
      responses:
        "200":
          description: JWT token
          schema:
            $ref: '#/definitions/handlers.AuthResult'
  /game/proposal/:round:
    get:
      description: Fetches a specific rule proposal
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: A rule proposal object
          schema:
            $ref: '#/definitions/handlers.ProposalObject'
  /game/propose:
    post:
      description: Submit a new rule proposal
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Proposed rule
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.RuleProposal'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.ProposalResult'
  /game/vars:
    get:
      description: Get game vars
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.VarsResult'
  /game/vote:
    post:
      description: Receive and tabulate votes, stage vote outcome to be processed when game window is settled
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
  /game/votes/:round:
    get:
      description: Fetches votes for a specific round
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of votes for a target round
          schema:
            $ref: '#/definitions/handlers.VotesList'
  /leaderboard:
    get:
      description: Leaderboard
      produces:
      - application/json
      responses:
        "200":
          description: List of players sorted by points
          schema:
            $ref: '#/definitions/handlers.PointsList'
  /ping:
    get:
      description: Ping/Health Check
      produces:
      - text/plain
      responses:
        "200":
          description: pong
          schema:
            type: string
  /players:
    get:
      description: Players
      produces:
      - application/json
      responses:
        "200":
          description: List of players in the current gameplay session
          schema:
            $ref: '#/definitions/handlers.PlayerList'
  /round:
    get:
      description: Players
      produces:
      - application/json
      responses:
        "200":
          description: The current round, 0 if game has not started, or -1 if no players are online
          schema:
            $ref: '#/definitions/handlers.CurrentRound'
  /rules/list:
    get:
      description: Rules
      produces:
      - application/json
      responses:
        "200":
          description: Current list of rules and their contents
          schema:
            $ref: '#/definitions/handlers.RuleList'
  /test:
    post:
      description: Run some arbitrary nomsu code
      parameters:
      - description: Nomsu code to run
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.TestInput'
      produces:
      - application/json
      responses:
        "200":
          description: Nomsu execution result
          schema:
            $ref: '#/definitions/handlers.TestResult'
swagger: "2.0"
